# Generated by Django 5.2.2 on 2025-06-12 18:37

import custom_user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', custom_user.models.CustomUserManager()),
            ],
        ),
    ]
