# Generated by Django 5.2.2 on 2025-06-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок объявления', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание автомобиля')),
                ('brand', models.CharField(help_text='Марка', max_length=100)),
                ('model', models.CharField(help_text='Модель', max_length=100)),
                ('generation', models.CharField(blank=True, help_text='Поколение (если нужно)', max_length=100)),
                ('year', models.PositiveSmallIntegerField(help_text='Год выпуска')),
                ('transmission', models.CharField(choices=[('AT', 'Автомат'), ('MT', 'Механика'), ('CVT', 'Вариатор'), ('AMT', 'Робот')], help_text='Коробка передач', max_length=20)),
                ('drive_type', models.CharField(choices=[('FWD', 'Передний'), ('RWD', 'Задний'), ('AWD', 'Полный')], help_text='Тип привода', max_length=20)),
                ('body_type', models.CharField(help_text='Кузов (седан, хэтчбек и т.д.)', max_length=20)),
                ('color', models.CharField(help_text='Цвет', max_length=50)),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('ev', 'Электро')], help_text='Тип двигателя', max_length=20)),
                ('engine_volume', models.DecimalField(decimal_places=1, help_text='Объем двигателя, л', max_digits=3)),
                ('horsepower', models.PositiveSmallIntegerField(help_text='Мощность, л.с.')),
                ('mileage', models.PositiveIntegerField(help_text='Пробег, км')),
                ('owners_count', models.PositiveSmallIntegerField(help_text='Количество владельцев')),
                ('vin', models.CharField(blank=True, help_text='VIN номер (опционально)', max_length=17)),
                ('is_new', models.BooleanField(default=False, help_text='Новый или с пробегом')),
                ('state', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('needs_repair', 'Требует ремонта')], help_text='Состояние', max_length=20)),
                ('pts_type', models.CharField(choices=[('original', 'Оригинал'), ('duplicate', 'Дубликат')], help_text='ПТС', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена, руб.', max_digits=10)),
                ('city', models.CharField(help_text='Город продажи', max_length=100)),
                ('address', models.CharField(blank=True, help_text='Адрес', max_length=200)),
                ('features', models.TextField(blank=True, help_text='Дополнительные опции и комплектация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Фотография автомобиля', upload_to='car_photos/')),
                ('is_primary', models.BooleanField(default=False, help_text='Главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(help_text='К какой машине привязано фото', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.car')),
            ],
        ),
    ]
