# Generated by Django 5.2.2 on 2025-06-13 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_carimage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, error_messages={'unique': 'A car with that vin is already exists.'}, help_text='VIN номер', max_length=17),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('vin',), name='car_vin_unique'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1500)), name='car_year_gte_1500'),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.CheckConstraint(condition=models.Q(('updated_at__gte', models.F('created_at'))), name='check_created_date'),
        ),
    ]
