# Generated by Django 5.2.2 on 2025-06-13 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_alter_car_vin_car_car_vin_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает проверки'), ('checked', 'Проверено'), ('listed', 'Размещено'), ('rejected', 'Отклонено')], default='draft', max_length=10, verbose_name='Статус заявки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий заказчика')),
                ('is_check', models.BooleanField(default=False, verbose_name='С проверкой или без')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.car', verbose_name='Автомобиль')),
                ('checker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_partner', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий партнёр')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
